### ISSUE TITLE
Persist session session to disk

### ISSUE THREAD

**Issue by realslimshanky-sh** [zytedata/zyte-smartproxy-puppeteer#3]
We can benefit from persisting Zyte Smart Proxy session ids on disk and reusing them during subsequent runs. [Zyte Proxy Headless Proxy](https://github.com/zytedata/zyte-smartproxy-headless-proxy) reduces load time by 5 to 10 seconds by reusing old unexpired sessions during reruns.

**Comment by geronsv** [comment]
Thanks for the suggestion!
We'll add this to our roadmap.
