### ISSUE TITLE
Plugin possible?

### ISSUE THREAD

**Issue by nickluger** [zytedata/zyte-smartproxy-puppeteer#6]
IDK whether that's possible, but this thing should probably be a plugin for puppeteer wit puppeteer as peer dependency and not some hard-coded, wrapped, own-version of puppeteer that locks you to  version`10.4.0`, where one depends on this lib to upgrade puppeteer. 

Especially when using other extensions on top of puppeteer like stealth.

**Comment by geronsv** [comment]
Thanks for the feedback!
We have it on our roadmap. No ETA yet.

**Comment by geronsv** [comment]
We now have a plugin compatible with both puppeteer-extra and playwright-extra.
https://github.com/zytedata/zyte-smartproxy-plugin
